### ISSUE TITLE
Rename Project to a Codename

### ISSUE THREAD

**Issue by CFIALeronB** [ai-cfia/membrane-backend#24]
**Description:**
The current name of our project, "Louis Login Backend," may not encapsulate the full essence and uniqueness of our single state sign-on solution. As our platform evolves, it's crucial that our name reflects our core functionalities and resonates with our users.

**Proposed Names:**
- CellGate
- PathGuard
- ViraShield
- StatePhage
- CytokineShield
- MacroGuard
(Please add more names as you see fit.)

**Criteria for Selection:**
1. The name should resonate with our project's main functionality - single state sign-on.
2. It should be easy to remember and pronounce.
3. Domain availability should be considered if we're thinking of setting up a dedicated website.
4. It should reflect our project's defense theme, possibly relating to virus-fighting bacteria.

**Next Steps:**
1. Collect feedback from the team on the proposed names.
2. Shortlist names based on feedback and criteria.
3. Finalize the name and initiate rebranding efforts.

Please share your thoughts and suggestions below.

**Comment by rngadam** [comment]
Settled on Membrane.

noun, plural: membranes. (1) (biology) A thin layer of tissue covering a surface or lining a cavity, space or organ. (2) (biology) A cell membrane. (3) (chemistry) A thin pliable sheet of material that is permeable to substances in solution.

same in French and English
